### ISSUE TITLE
Broken link to live demo

### ISSUE THREAD

**Issue by svgeesus** [adobe/balance-text#130]
### Expected Behaviour

Following the link from the readme to the demo does not 404

> See the demo provided or this online version for a working sample.
http://adobe-webplatform.github.io/balance-text/demo/index.html

### Actual Behaviour

404

#### Steps to Reproduce

follow link

**Comment by redmunds** [comment]
Thanks for reporting! We recently moved repo to a new org and I missed that link.

**Comment by redmunds** [comment]
Fixed with PR #131
