### ISSUE TITLE
Syntax error in Internet Explorer: arrow function

### ISSUE THREAD

**Issue by DavidOliver** [adobe/balance-text#132]
Thanks for balance-text. It makes a real difference, and I hope I can continue to use it in projects, even those that require IE support. :)

### Expected Behaviour

Works in IE, as per the comment in the source ('IE 9') and the guidance in the readme.

### Actual Behaviour

```
SCRIPT1002: Syntax error
balancetext.js (71,12)
```

#### Steps to Reproduce

Include the script in the HTML document and load in any version of Internet Explorer.

    <script src="https://cdnjs.cloudflare.com/ajax/libs/balance-text/3.3.0/balancetext.js"></script>

### More information

[Browser compatability information](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility)

[Offending line](https://github.com/adobe/balance-text/blob/v3.3.0/balancetext.js#L71)

**Comment by redmunds** [comment]
Hi @DavidOliver, thanks for using balance-text and reporting bugs. Oops, the section that says this was tested in 'IE 9' is for the `debounce` function and does not apply to the balance-text code:

```
 * Copyright (c) 2007-2009 unscriptable.com and John M. Hann
```

While it should not have been updated to use arrow functions, arrow functions are now used in many other places so it won't help to fix that 1 module. Unfortunately, I don't think it's worth supporting IE, so I probably won't fix this.

Note that older versions are still provided on the CDNs, so to support IE you need to change your link to v3.2.1 (and you should also be using the minified version for faster downloads):

[https://cdnjs.cloudflare.com/ajax/libs/balance-text/3.2.1/balancetext.min.js](https://cdnjs.cloudflare.com/ajax/libs/balance-text/3.2.1/balancetext.min.js)

Regards,
Randy Edmunds

**Comment by DavidOliver** [comment]
Ah - thanks for explaining.

The readme says "BalanceText is designed to run in most common browsers." Shall I submit a pull request to include the information in your reply above in the readme?

**Comment by Rycochet** [comment]
@DavidOliver IE is not a common browser by any definition - IE11 is the only partially supported version of IE (security fixes only, not new features - it's not exactly standards-compliant either).

If you're wanting to support non-standards-compliant browsers then the best choice is actually to make a bundle out of all needed libraries and run them through [babel](https://github.com/babel/babel) (just remember that it'll need configuring to support obsolete browsers, but is perfectly happy to do so).

**Comment by DavidOliver** [comment]
Well, by _some_ definitions it is. :) For example, IE11 unfortunately still commonly used in the education sector in the UK; it accounts for about 50% of the users of an app I work on.

I asked about the readme as I thought it may save others some time to know that recent versions don't work in IE.

**Comment by redmunds** [comment]
I was hoping that this bug report would be found by anyone having problems with IE.

Do you think it would be helpful if I changed the wording from "most common browsers" to "most modern browsers"?

**Comment by DavidOliver** [comment]
I expect it would, yes, but I suppose a short note on IE not being supported would be even better.

Thanks again for balance-text and clarifying!
