### ISSUE TITLE
Ability to disable/destroy?

### ISSUE THREAD

**Issue by andrewjireland** [adobe/balance-text#138]
Hi there, generally I find balance text works well on larger screen sizes but would like to disable it on mobile as I find the algorithm produces some undesirable formatting.

I'd planned to disable the balance-text function at a certain breakpoint\inside a resize listener, but then noticed there wasn't a method to do this in your documentation. Is there a recommended way I can do this, or will I need to fork my own version with a customised resize listener to achieve this?

Best,
Andrew

**Comment by redmunds** [comment]
You can remove elements from the watch list using `watch:false` option, for example:
```
  balanceText(".balance-text-custom", {watch: false});
```

There's a sample in the repo at: test/test-watch-unwatch.htm

Does that work?

**Comment by andrewjireland** [comment]
Hey @redmunds, thanks for your reply.

This would work, but I still wanted the balance text on resize above certain screen sizes. I.e. if someone on an iPad changed the orientation of the device I'd want to watch and rebalance the text, but if they were on a phone I'd rather not watch the resize event at all.

I ended up forking my own version and tweaking the `updateWatched` function with my own `window.width` condition in this instance.

**Comment by redmunds** [comment]
With existing code, you would have to conditionally watch or unwatch based on screen size.
