### ISSUE TITLE
Plugin balances text but calculates width incorrectly (regardless of html structure and/or css)

### ISSUE THREAD

**Issue by MaisonDeVolonte** [adobe/balance-text#141]
### Expected Behaviour
should calculate width based on the element's width
### Actual Behaviour
calculates it slightly wider than the actual size (every time, regardless of the css or html structure)
### Reproduce Scenario (including but not limited to)
https://www.royaltylasvegas.com/admin/templates/episode-item
#### Steps to Reproduce
open inspector
change css properties
resize window
balancetext plugin recalculates but always slightly off
#### Platform and Version
chrome
#### Logs taken while reproducing problem
miscalculates width
<img width="362" alt="Screen Shot 2020-09-19 at 5 43 35 PM" src="https://user-images.githubusercontent.com/11622069/93691856-1f982f00-faa0-11ea-989f-c6fd0af750a9.png">

balances text well (plain text)
<img width="615" alt="Screen Shot 2020-09-19 at 5 43 27 PM" src="https://user-images.githubusercontent.com/11622069/93691857-258e1000-faa0-11ea-906d-03bd02110f6f.png">

**Comment by MaisonDeVolonte** [comment]
Nevermind [facepalm] I didn't see the recommendation by @egbit in #75 - sorry about that. 

The css padding in my list items was causing the plugin to miscalculate. After wrapping the inner text with a span the plugin was able to work perfectly.

**Comment by redmunds** [comment]
@MaisonDeVolonte Thank you for followup information.
