### ISSUE TITLE
It breaks events and animations at every run

### ISSUE THREAD

**Issue by fregante** [adobe/balance-text#63]
I found that BT uses `.html()` extensively and that causes the loss of all child nodes and their attached event listeners, and it causes any running animations to stop.

I looked into the issue and it doesn't seem to have an easy fix. The major hurdle to overcome is the switch from searching break opportunities in a flat string to searching it across multiple nodes, particularly in "substringing" the DOM (`'hello <span>world</span>'.substr(0, 13)` is relatively easy on a string but not on the DOM).

Alternatively, we could leave the break opportunity algorithm alone and instead keep a copy of the existing DOM that will just get the `<br>`s once we find their places. The problem then would _only_ be matching the found `char index` in the DOM. But that is difficult too.

What do you suggest?

**Comment by bfred-it** [comment]
I think I got it, eventually. I applied the second suggestion. I'll be testing it.

**Comment by redmunds** [comment]
Thanks for update. I'm swamped this week, so not sure when I'll get a chance to look at this.

**Comment by bfred-it** [comment]
This is a partial solution. It's working for me but it might need 

- [ ] Justified text support
- [ ] cleanup
- [ ] commenting
